version: '3.8'
services:
  account-service:
    image: minskim2/jpetstore6/account-service:latest
    ports:
      - "8081:8081"
    extra_hosts:
      - "myhost:host-gateway"
    env_file:
      - ./common.env
      - ./account_service.env

  cart-service:
    image: minskim2/jpetstore6/cart-service:latest
    ports:
      - "8082:8082"
    extra_hosts:
      - "myhost:host-gateway"
    env_file:
      - ./common.env
      - ./cart_service.env

  catalog-service:
    image: minskim2/jpetstore6/catalog-service:latest
    ports:
      - "8083:8083"
    extra_hosts:
      - "myhost:host-gateway"
    env_file:
      - ./common.env
      - ./catalog_service.env

  order-service:
    image: minskim2/jpetstore6/order-service:latest
    ports:
      - "8084:8084"
    extra_hosts:
      - "myhost:host-gateway"
    env_file:
      - ./common.env
      - ./order_service.env